var XMLDocument=function(){var e=$("#inputICO").val(),f=$("#email").val(),a=$('input[name="typDokladu"]:checked').val(),d=$('select[name="typSW"]').val(),b,c=(new Date).toLocaleString("en-GB",{timeZone:"Europe/Bratislava"});"radioPokladna"==a&&"pohodaStormware"==d&&(b=this.PD_pohodaStormware(e,c));"radioIntDokl"==a&&"pohodaStormware"==d&&(b=this.IntD_pohodaStormware(e,c));this.sendForm(e,f,b)};
XMLDocument.prototype.PD_pohodaStormware=function(e,f){var a='<?xml version="1.0" encoding="UTF-8"?>\n<dat:dataPack version="2.0" id="PD_'+sessionStorage.length+'x" ico="'+e+'" application="uSkener" note="Import naskenovanych blockov" xmlns:dat="http://www.stormware.cz/schema/version_2/data.xsd" xmlns:vch="http://www.stormware.cz/schema/version_2/voucher.xsd" xmlns:typ="http://www.stormware.cz/schema/version_2/type.xsd">';for(var d=0;d<sessionStorage.length;d++){var b=JSON.parse(sessionStorage.getItem(d));
a+="\n\x3c!-- Pokladnicny doklad bez textovych poloziek --\x3e";a=a+'\n<dat:dataPackItem version="2.0" id="POK'+(d+1)+'">';a+='\n<vch:voucher version="2.0"><vch:voucherHeader><vch:voucherType>expense</vch:voucherType><vch:cashAccount><typ:ids>HP</typ:ids></vch:cashAccount>';var c=b.receipt.issueDate.split(" ")[0].split(".");a=a+"<vch:originalDocument>"+b.receipt.receiptNumber+"</vch:originalDocument>";a=a+"\n<vch:date>"+c[2]+"-"+c[1]+"-"+c[0]+"</vch:date>";a=a+"<vch:datePayment>"+c[2]+"-"+c[1]+"-"+
c[0]+"</vch:datePayment>";a=a+"<vch:dateTax>"+c[2]+"-"+c[1]+"-"+c[0]+"</vch:dateTax>";a+="\n<vch:classificationKVDPH><typ:ids>B3</typ:ids></vch:classificationKVDPH>";a=a+"<vch:text>"+b.receipt.receiptId+"</vch:text>";a+="\n\x3c!--adresa bez vazby na program POHODA--\x3e";a+="\n<vch:partnerIdentity><typ:address>";a=a+"<typ:company><![CDATA["+b.receipt.organization.name+"]]\x3e</typ:company>";a=a+"<typ:city>"+b.receipt.organization.municipality+"</typ:city>";a=a+"<typ:street>"+b.receipt.organization.streetName+
" "+b.receipt.organization.propertyRegistrationNumber+"</typ:street>";a=a+"<typ:zip>"+b.receipt.organization.postalCode+"</typ:zip>";a=a+"<typ:ico>"+b.receipt.organization.ico+"</typ:ico><typ:dic>"+b.receipt.organization.dic+"</typ:dic><typ:icDph>"+b.receipt.organization.icDph+"</typ:icDph>";a+="</typ:address></vch:partnerIdentity>";a=a+"<vch:intNote>Import PD vytvoreny vo web app uSkener dna "+f+"</vch:intNote></vch:voucherHeader>";a+="<vch:voucherSummary>";a+="<vch:homeCurrency>";c=(100*b.receipt.taxBaseReduced+
100*b.receipt.vatAmountReduced)/100;a=a+"<typ:priceHigh>"+b.receipt.taxBaseBasic+"</typ:priceHigh><typ:priceHighVAT>"+b.receipt.vatAmountBasic+"</typ:priceHighVAT><typ:priceHighSum>"+(100*b.receipt.taxBaseBasic+100*b.receipt.vatAmountBasic)/100+"</typ:priceHighSum>";a=a+"<typ:priceLow>"+b.receipt.taxBaseReduced+"</typ:priceLow><typ:priceLowVAT>"+b.receipt.vatAmountReduced+"</typ:priceLowVAT><typ:priceLowSum>"+c+"</typ:priceLowSum>";a=a+"<typ:priceNone>"+b.receipt.freeTaxAmount+"</typ:priceNone>";
a+="</vch:homeCurrency>";a+="</vch:voucherSummary>";a+="</vch:voucher></dat:dataPackItem>"}return a+"\n</dat:dataPack>"};
XMLDocument.prototype.IntD_pohodaStormware=function(e,f){var a='<?xml version="1.0" encoding="UTF-8"?>\n<dat:dataPack version="2.0" id="INT_'+sessionStorage.length+'x" ico="'+e+'" application="uSkener" note="Import naskenovanych blockov" xmlns:dat="http://www.stormware.cz/schema/version_2/data.xsd" xmlns:int="http://www.stormware.cz/schema/version_2/intDoc.xsd" xmlns:typ="http://www.stormware.cz/schema/version_2/type.xsd">';for(var d=0;d<sessionStorage.length;d++){var b=JSON.parse(sessionStorage.getItem(d));
a+="\n\x3c!-- Interny doklad bez textovych poloziek --\x3e";a=a+'\n<dat:dataPackItem version="2.0" id="INT'+(d+1)+'">';a+='\n<int:intDoc version="2.0"><int:intDocHeader>';var c=b.receipt.issueDate.split(" ")[0].split(".");a=a+"<int:symVar>"+b.receipt.receiptNumber+"</int:symVar>";a=a+"\n<int:date>"+c[2]+"-"+c[1]+"-"+c[0]+"</int:date>";a=a+"<int:dateTax>"+c[2]+"-"+c[1]+"-"+c[0]+"</int:dateTax>";a=a+"<int:dateAccounting>"+c[2]+"-"+c[1]+"-"+c[0]+"</int:dateAccounting>";a=a+"<int:dateDelivery>"+c[2]+
"-"+c[1]+"-"+c[0]+"</int:dateDelivery>";a=a+"<int:dateKVDPH>"+c[2]+"-"+c[1]+"-"+c[0]+"</int:dateKVDPH>";a+="\n<int:classificationVAT><typ:ids>UD</typ:ids></int:classificationVAT>";a+="\n<int:classificationKVDPH><typ:ids>B3</typ:ids></int:classificationKVDPH>";a=a+"<int:text>"+b.receipt.receiptId+"</int:text>";a+="\n\x3c!--adresa bez vazby na program POHODA--\x3e";a+="\n<int:partnerIdentity><typ:address>";a=a+"<typ:company><![CDATA["+b.receipt.organization.name+"]]\x3e</typ:company>";a=a+"<typ:city>"+
b.receipt.organization.municipality+"</typ:city>";a=a+"<typ:street>"+b.receipt.organization.streetName+" "+b.receipt.organization.propertyRegistrationNumber+"</typ:street>";a=a+"<typ:zip>"+b.receipt.organization.postalCode+"</typ:zip>";a=a+"<typ:ico>"+b.receipt.organization.ico+"</typ:ico><typ:dic>"+b.receipt.organization.dic+"</typ:dic><typ:icDph>"+b.receipt.organization.icDph+"</typ:icDph>";a+="</typ:address></int:partnerIdentity>";a+="<int:liquidation>true</int:liquidation>";a=a+"<int:intNote>Import INT vytvoreny vo web app uSkener dna "+
f+"</int:intNote></int:intDocHeader>";a+="<int:intDocSummary>";a+="<int:homeCurrency>";c=(100*b.receipt.taxBaseReduced+100*b.receipt.vatAmountReduced)/100;a=a+"<typ:priceHigh>"+b.receipt.taxBaseBasic+"</typ:priceHigh><typ:priceHighVAT>"+b.receipt.vatAmountBasic+"</typ:priceHighVAT><typ:priceHighSum>"+(100*b.receipt.taxBaseBasic+100*b.receipt.vatAmountBasic)/100+"</typ:priceHighSum>";a=a+"<typ:priceLow>"+b.receipt.taxBaseReduced+"</typ:priceLow><typ:priceLowVAT>"+b.receipt.vatAmountReduced+"</typ:priceLowVAT><typ:priceLowSum>"+
c+"</typ:priceLowSum>";a=a+"<typ:priceNone>"+b.receipt.freeTaxAmount+"</typ:priceNone>";a+="</int:homeCurrency>";a+="</int:intDocSummary>";a+="</int:intDoc></dat:dataPackItem>"}return a+"\n</dat:dataPack>"};
XMLDocument.prototype.sendForm=function(e,f,a){var d=[];localStorage.getItem("usedIco")?(d=JSON.parse(localStorage.getItem("usedIco")),d.includes(localStorage.getItem("tempIco"))||(5>=d.length||d.shift(),d.push(localStorage.getItem("tempIco")),localStorage.setItem("usedIco",JSON.stringify(d)))):(d.push(localStorage.getItem("tempIco")),localStorage.setItem("usedIco",JSON.stringify(d)));$.ajax({method:"POST",url:"mailer.php",data:"email="+encodeURIComponent(f)+"&xml="+encodeURIComponent(a)+"&ico="+
encodeURIComponent(e)+"&count="+encodeURIComponent(sessionStorage.length),dataType:"html",beforeSend:function(b){$("#emailModalLabel").html('\u010cakajte... <div class="spinner-border" role="status"><span class="visually-hidden">Loading...</span></div>');$("#emailModal .modal-footer").html('<button class="btn btn-primary" type="button" disabled><span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Odosielam...</button>')},success:function(b){$("#emailModal .modal-footer").html('<button type="button" class="btn btn-primary" data-bs-dismiss="modal">Hotovo</button>');
$("#emailModalLabel").html(b)}})};