var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(d){var e=0;return function(){return e<d.length?{done:!1,value:d[e++]}:{done:!0}}};$jscomp.arrayIterator=function(d){return{next:$jscomp.arrayIteratorImpl(d)}};$jscomp.makeIterator=function(d){var e="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];return e?e.call(d):$jscomp.arrayIterator(d)};
$(document).ready(function(){null!=localStorage.getItem("tempIco")&&$("#inputICO").val(localStorage.getItem("tempIco"));null!=localStorage.getItem("email")&&$("#email").val(localStorage.getItem("email"));if(null!=localStorage.getItem("usedIco"))for(var d=JSON.parse(localStorage.getItem("usedIco")),e=d.length;0<e;e--)$("#usedIco").append('<option value="'+d[e-1]+'">');$("#inputICO").change(function(){localStorage.setItem("tempIco",$("#inputICO").val())});$("#email").change(function(){localStorage.setItem("email",
$("#email").val())})});function checkStorageLength(d){50<=sessionStorage.length?($("#detailModalLabel").html("M\u00e1te v pam\u00e4ti ulo\u017een\u00fdch 50 dokladov na import! Uvo\u013enite pam\u00e4\u0165 a pokra\u010dujte v skenovan\u00ed."),$("#BlocekFooter").html('<button id="breakScan" class="btn btn-lg btn-primary" data-bs-dismiss="modal">PRERU\u0160I\u0164</button>')):scan(d)}
function scan(d){var e=setInterval(function(){if(1==$("#detailModal").hasClass("show")){$("#blocekHeader button").remove();$("#BlocekFooter").html("");$("#detailModalLabel").html("Prehliada\u010du mus\u00edte povoli\u0165 pr\u00edstup ku kamere.");$("#blocekDetail").html("");$("#BlocekFooter").html('<button id="breakScan" class="btn btn-lg btn-primary" data-bs-dismiss="modal">PRERU\u0160I\u0164</button>');document.getElementById("breakScan").addEventListener("click",function(){d.stop()});$("#videoContainer").show();
var c=document.getElementById("blocekModalBody").offsetWidth;document.getElementById("qr-video").style.width=c+"px";d.start();clearInterval(e)}},100)}
function getBlocek(d,e){d.stop();$("#videoContainer").hide();$("#blocekDetail").html("");$("#BlocekFooter").html("");if(/^\w-/.test(e))var c='{"receiptId":"'+e+'"}';else if(5==e.split(":").length)c=e.split(":"),c='{"okp":"'+c[0]+'","cashRegisterCode":"'+c[1]+'","issueDateFormatted":"'+(c[2][4]+c[2][5]+"."+c[2][2]+c[2][3]+".20"+c[2][0]+c[2][1]+" "+c[2][6]+c[2][7]+":"+c[2][8]+c[2][9]+":"+c[2][10]+c[2][11])+'","receiptNumber":'+c[3]+',"totalAmount":'+c[4]+"}";else{$("#detailModal .modal-content").prepend('<div class="modal-header" id="blocekHeader"><h6 class="modal-title" id="detailModalLabel">Error</h6></div>');
$("#blocekDetail").html("Tento typ dokladu nie je zatia\u013e podporovan\u00fd. Treba ho nahra\u0165 do u\u010dtovn\u00edctva manu\u00e1lne.");$("#blocekHeader").append('<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>');$("#BlocekFooter").append('<button class="btn btn-primary" data-bs-dismiss="modal">ZAVRIE\u0164</button>');return}$.ajax({type:"POST",url:"https://ekasa.financnasprava.sk/mdu/api/v1/opd/receipt/find",data:c,contentType:"application/json; charset=utf-8",
dataType:"json",error:function(a){a=JSON.parse(a.responseText);-1==a.returnValue&&($("#detailModal .modal-content").prepend('<div class="modal-header" id="blocekHeader"><h6 class="modal-title" id="detailModalLabel">Error</h6></div>'),$("#blocekDetail").html(a.errorDescription),$("#blocekHeader").append('<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>'),$("#BlocekFooter").append('<button class="btn btn-primary" data-bs-dismiss="modal">ZAVRIE\u0164</button>'))},
success:function(a){if(0==a.returnValue&&null==a.receipt)$("#detailModal .modal-content").prepend('<div class="modal-header" id="blocekHeader"><h6 class="modal-title" id="detailModalLabel">Error</h6></div>'),$("#blocekDetail").html("Doklad sme nena\u0161li v syst\u00e9me eKasa. Budete ho musie\u0165 za\u00fa\u010dtova\u0165 manu\u00e1lne."),$("#blocekHeader").append('<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>'),$("#BlocekFooter").append('<button class="btn btn-primary" data-bs-dismiss="modal">ZAVRIE\u0164</button>');
else try{$("#detailModal .modal-content").prepend('<div class="modal-header" id="blocekHeader"><h6 class="modal-title" id="detailModalLabel">'+a.receipt.receiptId+"</h6></div>");var b="<table><tr><td>"+a.receipt.organization.name+"</td></tr>";null==a.receipt.organization.propertyRegistrationNumber&&(a.receipt.organization.propertyRegistrationNumber=a.receipt.organization.buildingNumber);b=b+"<tr><td>"+a.receipt.organization.streetName+" "+a.receipt.organization.propertyRegistrationNumber+"</td></tr>";
b=b+"<tr><td>"+a.receipt.organization.postalCode+" "+a.receipt.organization.municipality+"</td></tr>";b=b+"<tr><td> DI\u010c: "+a.receipt.organization.dic+"</td></tr>";null==a.receipt.organization.icDph&&(a.receipt.organization.icDph="");b=b+"<tr><td> I\u010c DPH: "+a.receipt.organization.icDph+"</td></tr>";b=b+"<tr><td> I\u010cO: "+a.receipt.organization.ico+"</td></tr>";b=b+'<tr><td style="padding-top:5px;"> D\u00e1tum a \u010das vyhotovenia: '+a.receipt.createDate+"</td></tr>";b=b+'<tr><td style="padding-top:5px;"> Poradov\u00e9 \u010d\u00edslo: '+
a.receipt.receiptNumber+"</td></tr>";b=b+'<tr><td style="padding:5px 0;"> Celkov\u00e1 suma dokladu: '+a.receipt.totalPrice+" \u20ac</td></tr></table>";null==a.receipt.taxBaseBasic&&(a.receipt.taxBaseBasic=0);null==a.receipt.vatAmountBasic&&(a.receipt.vatAmountBasic=0);null==a.receipt.taxBaseReduced&&(a.receipt.taxBaseReduced=0);null==a.receipt.vatAmountReduced&&(a.receipt.vatAmountReduced=0);null==a.receipt.freeTaxAmount&&(a.receipt.freeTaxAmount=0);b+='<table><tr style="border-top:1pt solid black; padding-bottom:5px;"><td>Sadzba:</td><td>Bez DPH:</td><td>DPH</td></tr>';
b=b+"<tr><td>20%:</td><td>"+a.receipt.taxBaseBasic+" \u20ac</td><td>"+a.receipt.vatAmountBasic+" \u20ac</td></tr>";b=b+"<tr><td>10%</td><td>"+a.receipt.taxBaseReduced+" \u20ac</td><td>"+a.receipt.vatAmountReduced+" \u20ac</td></tr>";b=b+'<tr style="border-bottom:1pt solid black;"><td>IN\u00c9:</td><td>'+a.receipt.freeTaxAmount+" \u20ac</td><td></td></tr></table>";b+="<table>";for(var h=$jscomp.makeIterator(Object.entries(a.receipt.items)),g=h.next();!g.done;g=h.next()){var k=$jscomp.makeIterator(g.value);
k.next();var f=k.next().value;b=b+'<tr><td colspan="3" style="font-weight:600;">'+f.name+"</td></tr>";b=b+'<tr><td style="width: 33.33%;">'+f.quantity+' x</td><td style="width: 33.33%;">'+f.vatRate+'%</td><td style="width: 33.33%;">'+f.price+" \u20ac</td></tr>"}b+="</table>";$("#blocekDetail").append(b);$("#BlocekFooter").append('<button id="AddBlocek" class="btn btn-lg btn-primary" data-bs-dismiss="modal">ULO\u017dI\u0164</button>');document.getElementById("AddBlocek").addEventListener("click",function(){var l=
sessionStorage.length;delete a.receipt.items;sessionStorage.setItem(l,JSON.stringify(a));$("#blocekDetail").html("");$("#BlocekFooter").html("");$("#results").val("naskenovan\u00fdch "+sessionStorage.length+" / 50");$("#results").removeClass("is-invalid is-valid")});$("#BlocekFooter").append('<button class="btn btn-lg btn-secondary" data-bs-dismiss="modal">ZAHODI\u0164</button>')}catch(l){$("#detailModal .modal-content").prepend('<div class="modal-header" id="blocekHeader"><h6 class="modal-title" id="detailModalLabel">Nastala neo\u010dak\u00e1van\u00e1 chyba</h6></div>'),
$("#blocekDetail").html("Pokra\u010dujte s in\u00fdm dokladom. Ak sa nejedn\u00e1 o doklad k \u00fahrade fakt\u00fary, tak n\u00e1m pr\u00edpadne fotok\u00f3piu po\u0161lite na email@uskener.sk"),$("#blocekHeader").append('<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>'),$("#BlocekFooter").append('<button class="btn btn-primary" data-bs-dismiss="modal">ZAVRIE\u0164</button>')}}})}
function clearMemory(){sessionStorage.clear();$("#clearModal").modal("hide");$("#results").val("naskenovan\u00fdch "+sessionStorage.length+" / 50");$("#results").removeClass("is-invalid is-valid")}function completeVoucher(){validateEmail()&&new XMLDocument}
function proceedVoucher(){validateIco()&&validateQueue()&&($("#emailModalLabel").html("Skonvertovan\u00e9 d\u00e1ta sa odo\u0161l\u00fa ako pr\u00edloha na uveden\u00fd email"),$("#emailModal .modal-footer").html('<button type="button" class="btn btn-primary" onclick=completeVoucher()>Odo\u0161li</button>'),$("#emailModal").modal("show"))};